@host=http://localhost:3333

###
POST {{host}}/transactions
Content-Type: application/json

{
  "title": "Salário",
  "amount": 3000,
  "type": "credit"
}

###
GET {{host}}/transactions
Content-Type: application/json

###
GET {{host}}/transactions/ed01f487-af2d-435d-9668-aed6e4091904
Content-Type: application/json

###
