@host= http://localhost:3333

###
GET {{host}}/users

###
POST {{host}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com"
}


###
DELETE {{host}}/users/64fcccac-df86-42a0-baf2-beb541151089
