name: Run Unit Tests On Project 03 Lessons

on:
  pull_request:
    branches: [ main ]

jobs:
  run-unit-tests:
    defaults:
      run:
        working-directory: nodejs/03-api-solid
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        environment:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: apisolid
        ports:
          - 5432:5432


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm test:e2e
        env:
          JWT_SECRET: "test-environment"
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"

